const Types = {
  GET_APP_DATA: 'GET_APP_DATA',
  GET_USER_DATA: 'GET_USER_DATA',
  OPEN_CART: 'OPEN_CART',
  CLOSE_CART: 'CLOSE_CART',
  CHECKOUT: 'CHECKOUT',
  PAYMENT_CONFIRM: 'PAYMENT_CONFIRM'
}

export default Types
